# Generated by Django 5.2 on 2025-04-29 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraria', '0004_livro'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='autores',
            field=models.ManyToManyField(related_name='livros', to='livraria.autor'),
        ),
    ]
